### ISSUE TITLE
Status of the app

### ISSUE THREAD

**Issue by lislis** [call-a3/Sailfish-Slack#2]
Hey there!
I wanted to what the status of the app is? Are you still interested in further working on it? Did you publish it somewhere?
Cheers!

**Comment by call-a3** [comment]
Hi @lislis! Thanks for your interest in this!
I'm incredibly busy with work and other projects. As a side-effect I haven't made much progress. (I'm sure a lot of people will recognize the situation. :/ ) Right now this is just a skeleton app, so a lot of work is still required to make this anywhere near usefull. So that's it for your first question about the current status. (This also resolves your third question: it's not published anywhere because it's not even a working prototype yet...)

To answer your second question: YES! I'm still very interested in working on this. I also have to acknowledge my weaknesses here: This is my first app in SailfishOS, using QML, ... so everything's new for me. I use a lot of trial-and-error and probably a lot of people with more experience could develop this much faster than me. Consider this a kind request to work on this yourself if you are able and willing, or talk to anyone you might know who would fit those criteria ;)

I'm willing to give anyone who commits some useful pull requests full commit access to this repo so this project makes more progress!

**Comment by lislis** [comment]
Thanks for the answer! 
I'm also completely new to the Sailfish ecosystem and QML but this app would definitely be a reason for me to read up on these things and help contributing.
Thanks again!

**Comment by norayr** [comment]
hey. I need very basic functionality - ability to chat in the channels. I do not want to run non native Sailfish apps - in fact, right now I have no working alien dalvik, and I need open source application even if it has limited functionality.

I believe, if you put existing app to openrepos.net, it will draw attention of developers to your github repository and will increase possibility of future pull requests.
